### ISSUE TITLE
"Loading..." hangs on launch after parsing "tag_name" in a plugin

### ISSUE THREAD

**Issue by pauleveritt** [simonw/datasette-app#139]
Performs “Installing collected packages” on a bunch of things, prints “Took 6582ms”, and (a) the spinner remains and (b) I don’t get an HTML window.

macOS 12.3.1 and Datasette Desktop 0.2.1

```
Contents % ./MacOS/Datasette 
2022-04-13 11:05:26.974 Datasette[22379:524351] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
feedURL https://update.electronjs.org/simonw/datasette-app/darwin-x64/0.2.1
requestHeaders { 'User-Agent': 'update-electron-app/2.0.1 (darwin: x64)' }
/Users/pauleveritt/.datasette-app/venv/bin/python3.9 [ '--version' ]
checking-for-update
/Users/pauleveritt/.datasette-app/venv/bin/python3.9 [ '--version' ]
/Users/pauleveritt/.datasette-app/venv/bin/pip [
  'install',
  'datasette>=0.59a2',
  'datasette-app-support>=0.11.5',
  'datasette-vega>=0.6.2',
  'datasette-cluster-map>=0.17.1',
  'datasette-pretty-json>=0.2.1',
  'datasette-edit-schema>=0.4',
  'datasette-configure-fts>=1.1',
  'datasette-leaflet>=0.2.2',
  '--disable-pip-version-check'
]
update-not-available
{
  message: 'Traceback (most recent call last):',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.085Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/bin/datasette", line 8, in <module>',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '    sys.exit(cli())',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '    return self.main(*args, **kwargs)',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '    rv = self.invoke(ctx)',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '    return _process_result(sub_ctx.command.invoke(sub_ctx))',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.086Z
}
{
  message: '    return ctx.invoke(self.callback, **ctx.params)',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    return __callback(*args, **kwargs)',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/datasette/cli.py", line 582, in serve',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    asyncio.get_event_loop().run_until_complete(ds.invoke_startup())',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Applications/Datasette.app/Contents/Resources/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    return future.result()',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/datasette/app.py", line 384, in invoke_startup',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    await await_me_maybe(hook)',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/datasette/utils/__init__.py", line 111, in await_me_maybe',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    value = await value',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '  File "/Users/pauleveritt/.datasette-app/venv/lib/python3.9/site-packages/datasette_app_support/__init__.py", line 44, in inner',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: '    < version.parse(plugin["tag_name"])',
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
{
  message: "KeyError: 'tag_name'",
  type: 'stderr',
  ts: 2022-04-13T15:05:31.087Z
}
```

**Comment by antm** [comment]
I'm also experiencing it hung up on "Loading" but with different messaging. 

Mac (M1) on 12.3.1
Datasette Version 0.2.1 

```
bin/python3.9 --version
Python 3.9.6
Took 106ms
bin/python3.9 --version
Python 3.9.6
Took 105ms
bin/pip install datasette>=0.59a2 datasette-app-support>=0.11.5 datasette-vega>=0.6.2 datasette-cluster-map>=0.17.1 datasette-pretty-json>=0.2.1 datasette-edit-schema>=0.4 datasette-configure-fts>=1.1 datasette-leaflet>=0.2.2 --disable-pip-version-check
Requirement already satisfied: datasette>=0.59a2 in lib/python3.9/site-packages (0.61.1)
Requirement already satisfied: datasette-app-support>=0.11.5 in lib/python3.9/site-packages (0.11.5)
Requirement already satisfied: datasette-vega>=0.6.2 in lib/python3.9/site-packages (0.6.2)
Requirement already satisfied: datasette-cluster-map>=0.17.1 in lib/python3.9/site-packages (0.17.2)
Requirement already satisfied: datasette-pretty-json>=0.2.1 in lib/python3.9/site-packages (0.2.1)
Requirement already satisfied: datasette-edit-schema>=0.4 in lib/python3.9/site-packages (0.4)
Requirement already satisfied: datasette-configure-fts>=1.1 in lib/python3.9/site-packages (1.1)
Requirement already satisfied: datasette-leaflet>=0.2.2 in lib/python3.9/site-packages (0.2.2)
Requirement already satisfied: pluggy<1.1,>=1.0 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.0.0)
Requirement already satisfied: mergedeep<1.4.0,>=1.1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.3.4)
Requirement already satisfied: asgi-csrf>=0.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.9)
Requirement already satisfied: click-default-group~=1.2.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.2.2)
Requirement already satisfied: janus<1.1,>=0.6.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.0.0)
Requirement already satisfied: PyYAML<7.0,>=5.3 in lib/python3.9/site-packages (from datasette>=0.59a2) (6.0)
Requirement already satisfied: hupper~=1.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.10.3)
Requirement already satisfied: uvicorn~=0.11 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.17.6)
Requirement already satisfied: httpx>=0.20 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.22.0)
Requirement already satisfied: itsdangerous<3.0,>=1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (2.1.2)
Requirement already satisfied: asgiref<3.6.0,>=3.2.10 in lib/python3.9/site-packages (from datasette>=0.59a2) (3.5.0)
Requirement already satisfied: pint~=0.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.19.1)
Requirement already satisfied: click<8.1.0,>=7.1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (8.0.4)
Requirement already satisfied: Jinja2<3.1.0,>=2.10.3 in lib/python3.9/site-packages (from datasette>=0.59a2) (3.0.3)
Requirement already satisfied: aiofiles<0.9,>=0.4 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.8.0)
Requirement already satisfied: python-baseconv==1.2.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.2.2)
Requirement already satisfied: sqlite-utils in lib/python3.9/site-packages (from datasette-app-support>=0.11.5) (3.26)
Requirement already satisfied: packaging in lib/python3.9/site-packages (from datasette-app-support>=0.11.5) (21.3)
Requirement already satisfied: python-multipart in lib/python3.9/site-packages (from asgi-csrf>=0.9->datasette>=0.59a2) (0.0.5)
Requirement already satisfied: certifi in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (2021.10.8)
Requirement already satisfied: charset-normalizer in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (2.0.12)
Requirement already satisfied: sniffio in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (1.2.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (1.5.0)
Requirement already satisfied: httpcore<0.15.0,>=0.14.5 in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (0.14.7)
Requirement already satisfied: h11<0.13,>=0.11 in lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (0.12.0)
Requirement already satisfied: anyio==3.* in lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (3.5.0)
Requirement already satisfied: idna>=2.8 in lib/python3.9/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (3.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in lib/python3.9/site-packages (from janus<1.1,>=0.6.2->datasette>=0.59a2) (4.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in lib/python3.9/site-packages (from Jinja2<3.1.0,>=2.10.3->datasette>=0.59a2) (2.1.1)
Requirement already satisfied: sqlite-fts4 in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (1.0.1)
Requirement already satisfied: python-dateutil in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (2.8.2)
Requirement already satisfied: tabulate in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (0.8.9)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in lib/python3.9/site-packages (from packaging->datasette-app-support>=0.11.5) (3.0.8)
Requirement already satisfied: six>=1.5 in lib/python3.9/site-packages (from python-dateutil->sqlite-utils->datasette-app-support>=0.11.5) (1.16.0)
Took 481ms
```

**Comment by dubmassacre** [comment]
I'm also experiencing this. Application hangs. 
Mac (intel) on macos BigSur 11.6.5 / Datasette Version 0.2.1

<img width="181" alt="image" src="https://user-images.githubusercontent.com/19786606/165938085-095e3887-5822-44a0-9d62-051e7757aad2.png">


bin/python3.9 --version
Python 3.9.6
Took 472ms
bin/python3.9 --version
Python 3.9.6
Took 402ms
bin/pip install datasette>=0.59a2 datasette-app-support>=0.11.5 datasette-vega>=0.6.2 datasette-cluster-map>=0.17.1 datasette-pretty-json>=0.2.1 datasette-edit-schema>=0.4 datasette-configure-fts>=1.1 datasette-leaflet>=0.2.2 --disable-pip-version-check
Requirement already satisfied: datasette>=0.59a2 in lib/python3.9/site-packages (0.61.1)
Requirement already satisfied: datasette-app-support>=0.11.5 in lib/python3.9/site-packages (0.11.5)
Requirement already satisfied: datasette-vega>=0.6.2 in lib/python3.9/site-packages (0.6.2)
Requirement already satisfied: datasette-cluster-map>=0.17.1 in lib/python3.9/site-packages (0.17.2)
Requirement already satisfied: datasette-pretty-json>=0.2.1 in lib/python3.9/site-packages (0.2.1)
Requirement already satisfied: datasette-edit-schema>=0.4 in lib/python3.9/site-packages (0.4)
Requirement already satisfied: datasette-configure-fts>=1.1 in lib/python3.9/site-packages (1.1)
Requirement already satisfied: datasette-leaflet>=0.2.2 in lib/python3.9/site-packages (0.2.2)
Requirement already satisfied: click<8.1.0,>=7.1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (8.0.4)
Requirement already satisfied: pluggy<1.1,>=1.0 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.0.0)
Requirement already satisfied: hupper~=1.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.10.3)
Requirement already satisfied: PyYAML<7.0,>=5.3 in lib/python3.9/site-packages (from datasette>=0.59a2) (6.0)
Requirement already satisfied: uvicorn~=0.11 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.17.6)
Requirement already satisfied: mergedeep<1.4.0,>=1.1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.3.4)
Requirement already satisfied: asgi-csrf>=0.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.9)
Requirement already satisfied: click-default-group~=1.2.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.2.2)
Requirement already satisfied: aiofiles<0.9,>=0.4 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.8.0)
Requirement already satisfied: python-baseconv==1.2.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.2.2)
Requirement already satisfied: Jinja2<3.1.0,>=2.10.3 in lib/python3.9/site-packages (from datasette>=0.59a2) (3.0.3)
Requirement already satisfied: itsdangerous<3.0,>=1.1 in lib/python3.9/site-packages (from datasette>=0.59a2) (2.1.2)
Requirement already satisfied: asgiref<3.6.0,>=3.2.10 in lib/python3.9/site-packages (from datasette>=0.59a2) (3.5.0)
Requirement already satisfied: pint~=0.9 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.19.2)
Requirement already satisfied: httpx>=0.20 in lib/python3.9/site-packages (from datasette>=0.59a2) (0.22.0)
Requirement already satisfied: janus<1.1,>=0.6.2 in lib/python3.9/site-packages (from datasette>=0.59a2) (1.0.0)
Requirement already satisfied: packaging in lib/python3.9/site-packages (from datasette-app-support>=0.11.5) (21.3)
Requirement already satisfied: sqlite-utils in lib/python3.9/site-packages (from datasette-app-support>=0.11.5) (3.26)
Requirement already satisfied: python-multipart in lib/python3.9/site-packages (from asgi-csrf>=0.9->datasette>=0.59a2) (0.0.5)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (1.5.0)
Requirement already satisfied: certifi in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (2021.10.8)
Requirement already satisfied: sniffio in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (1.2.0)
Requirement already satisfied: httpcore<0.15.0,>=0.14.5 in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (0.14.7)
Requirement already satisfied: charset-normalizer in lib/python3.9/site-packages (from httpx>=0.20->datasette>=0.59a2) (2.0.12)
Requirement already satisfied: anyio==3.* in lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (3.5.0)
Requirement already satisfied: h11<0.13,>=0.11 in lib/python3.9/site-packages (from httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (0.12.0)
Requirement already satisfied: idna>=2.8 in lib/python3.9/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx>=0.20->datasette>=0.59a2) (3.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in lib/python3.9/site-packages (from janus<1.1,>=0.6.2->datasette>=0.59a2) (4.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in lib/python3.9/site-packages (from Jinja2<3.1.0,>=2.10.3->datasette>=0.59a2) (2.1.1)
Requirement already satisfied: python-dateutil in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (2.8.2)
Requirement already satisfied: sqlite-fts4 in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (1.0.1)
Requirement already satisfied: tabulate in lib/python3.9/site-packages (from sqlite-utils->datasette-app-support>=0.11.5) (0.8.9)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in lib/python3.9/site-packages (from packaging->datasette-app-support>=0.11.5) (3.0.8)
Requirement already satisfied: six>=1.5 in lib/python3.9/site-packages (from python-dateutil->sqlite-utils->datasette-app-support>=0.11.5) (1.16.0)
Took 1649ms

**Comment by spod** [comment]
This appears to be an issue checking for updates online (one of the plugins is missing a data field which is causing the embedded webserver to start).

These steps should be a workable work around:

0. Download Datasette.app
1. Enter airplane mode (go offline)
2. Launch Datasette.app
3. Leave airplane mode (go back online)

**Comment by spod** [comment]
@tf13 https://github.com/simonw/datasette-app-support/pull/20 fixes it for me. Applying it locally should be a one time edit to `~/.datasette-app/venv/lib/python3.9/site-packages/datasette_app_support/__init__.py` until it or a similar fix is releases.

**Comment by kalmir** [comment]
I encounter the same problem. If I use the "temporarily disconnect" workaround, I am still unable to install plugin or make Tailscale work - because of this, I think but am not sure. I don't know what exactly change in `__init__.py` to fix the bug.

If I launch Datasette instance from CLI... Is there a way to replicate the access control - "anyone on my networks" setting? Thanks.
