### ISSUE TITLE
Be smarter about remembering which files you were working on after an app restart

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#54]
*Original title:  Integrate with recent files menu*

The recent files menu shows up when you right click on the Dock icon, and can also integrate with e.g. the history menu. When a file from that list is selected the `open-file` event is sent to the application.

**Comment by simonw** [comment]
Two parts to this: first, add `app.addRecentDocument(filepath);` to the code that opens files, e.g. these two bits:

https://github.com/simonw/datasette-app/blob/55f63b1fd820f19e752e035fd221a51aa0acaacb/main.js#L299-L301

https://github.com/simonw/datasette-app/blob/55f63b1fd820f19e752e035fd221a51aa0acaacb/main.js#L331-L333

The harder part is to add handling for the `open-file` event - this needs to be at the base level of the module:

```script
app.on("open-file", function (event, filepath) {
  console.log(event, filepath);
});
```

**Comment by simonw** [comment]
https://twitter.com/webology/status/1435471527688953857
> Some type of recently opened databases/files list would be nice too. I closed/re-opened (which is almost instant btw) and I understand what temporary means, but I kind of expected a list of recently open databases.

**Comment by simonw** [comment]
This is about more than just the "recent files" feature - a general usability problem right now is that it's very easy to quit the app and come back again and have to rebuild state from scratch. Need to do better than that!

**Comment by jefftriplett** [comment]
Because Twitter, I started a new database. When I re-opened it, I expected to see it in the list where "temporary" database is, but I had to search for it. I think this was in the same folder as my CSV file, but I'd have to double-check it.

**Comment by simonw** [comment]
Related: #42 - "If you open a CSV and then install a plugin the CSV table vanishes"

**Comment by mnckapilan** [comment]
I'm a novice trying to get some progress on this issue – and would love some advice – what would be the idiomatic way to persist user-specific details (like a list of recent files) within the Electron app? 

Right now the most similar functionality I notice is the list of plugins installed, but that's stored and is queried from DatasetteServer itself – or would we want to persist it at the Electron-level using something like [this](https://github.com/sindresorhus/electron-store) rather than the python level?

**Comment by simonw** [comment]
@mnckapilan I'm planning to more-or-less implement https://www.electronjs.org/docs/tutorial/recent-documents - which ties into the operating system's own concept of "recently opened files". I may go a step further than that though, perhaps having the default index page of the app also display that list to help people get back to what they were doing?

**Comment by mnckapilan** [comment]
I've made a primitive attempt at addressing this (for recently opened CSVs), though some refactoring is likely necessary to extend this to recent databases and newly created databases.

This is my very first attempt at contributing to open-source, so I do apologise if I'm missed something along the way!

**Comment by mnckapilan** [comment]
Was looking around for patterns on how different applications deal with recently opened items. VSCode takes an approach of separating their 2 recent types – individual files and folders – and also gives the option of reopening closed workspace.

![Screenshot 2021-09-08 at 10 34 46 pm](https://user-images.githubusercontent.com/16018395/132589134-6dd87eed-54d8-465e-a89e-f5ce57413611.png)


Something similar could be implemented for distinguishing between recently opened _CSVs_ and _databases_.

I've added a file menu option for recently opened CSVs to the #77, yet to extend it to databases.

**Comment by simonw** [comment]
I'm going to include part of the list of recent files on the homepage redesign in #91.

**Comment by simonw** [comment]
> I'm going to include part of the list of recent files on the homepage redesign in #91.

Turns out I couldn't find a way to gain access to that list of recent files in a way that would let me feature them in the hompage, so I left them in the "File -> Open Recent" sub-menu instead.
