### ISSUE TITLE
Show a visible log on first launch loading screen

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#70]
First launch is slow because it's installing Datasette. Having a greyed-out tail of the console commands being executed would help people understand what is going on rather than thinking the app could be broken - and with a tiny bit of extra copy can help explain that this is a first-launch-only delay.

**Comment by simonw** [comment]
This is also going to make it much easier to debug problems when the app gets stuck on the loading screen.

**Comment by simonw** [comment]
Here's what it looks like:

https://user-images.githubusercontent.com/9599/132914155-ba9cf4aa-3829-4f19-92a1-dcfc13f8c9d6.mov

**Comment by simonw** [comment]
I'm going to hide the "pip" warning, because I don't want to constantly run `pip install -U pip` and take a network hit just to get rid of that ugly warning message.

**Comment by abdusco** [comment]
@simonw You can call `pip` with a flag to disable the version warning:

```shell
pip --disable-pip-version-check
```
