### ISSUE TITLE
"Plugin installed" message box should say which plugin was installed

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#73]
@psychemedia: https://github.com/simonw/datasette-app/discussions/67#discussioncomment-1295147

> - plugin installed confirmation dialog - maybe name which plugin was installed?
![image](https://user-images.githubusercontent.com/82988/132478351-ca48476f-c948-4bdc-a4bd-2a38b898ae12.png)

**Comment by psychemedia** [comment]
This also makes me think should the plugin version number be displayed, and from that, how might a user be alerted to the fact that an updated version of the plugin might be available?
