### ISSUE TITLE
Better plugin installation interface (plugin directory)

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-app#74]
I punted on this in #5 - see also this suggestion from @psychemedia in https://github.com/simonw/datasette-app/discussions/67#discussioncomment-1295147

> - plugins: it would be handy to be able to select a plugin to install from a list. Gephi desktop used to have a two panel view to select plugins: available and uninstalled plugins in the left hand panel, installed plugins in the right. IIRC, each list had a check box by each item: check items in left and click *Install* to install, check items in right and click *Uninstall* to uninstall.

- [x] https://github.com/simonw/datasette-app/issues/100
- [x] https://github.com/simonw/datasette-app/issues/103
- [x] https://github.com/simonw/datasette-app/issues/72
- [x] https://github.com/simonw/datasette-app-support/issues/12
- [x] https://github.com/simonw/datasette-app-support/issues/11
- [x] https://github.com/simonw/datasette-app-support/issues/13

**Comment by simonw** [comment]
I can hit the API for https://datasette.io/content/plugins ( https://datasette.io/content/plugins.json ) to get the data. Would it be useful to filter that down to just the plugins that are known to work well with Datasette Desktop though?

I'm inclined not to do that. If a plugin doesn't work well with Datasette Desktop that's a bug in the plugin that should be fixed. Even the ones you wouldn't expect to be useful (`datasette-publish-fly` for example) are still useful if the documentation helps the user figure out how to run `~/.datasette-app/venv/bin/datasette`.

**Comment by psychemedia** [comment]
Could you use something like italics to show extensions that don't work in the app?

**Comment by simonw** [comment]
New menu item:
```diff
+        {
+          label: "Install Plugins…",
+          click() {
+            let newWindow = new BrowserWindow(windowOpts());
+            newWindow.loadFile("plugins.html");
+            configureWindow(newWindow);
+          },
+        },
```

**Comment by simonw** [comment]
Here's a fun idea: what if the list of plugins you could install was a very lightly customized Datasette table? Would get search and faceting for free, and help people further understand what the tool can be used for.

Could be pre-populated in the `temporary` database perhaps?

**Comment by simonw** [comment]
Uninstall work will happen in #72.

**Comment by simonw** [comment]
Each plugin should also show which version you have installed, what the latest version is and provide the option to upgrade.

The install status facet can have an extra value for upgradable.

**Comment by simonw** [comment]
An "upgrade all" button would be good too.

**Comment by simonw** [comment]
For the next release I'm going to implement "upgrade" but I won't fix "uninstall" - because uninstall requires a complex additional layer of persistence to avoid re-installing default plugins, see #101.

**Comment by simonw** [comment]
I'm dropping the "compatible with Datasette Desktop" feature for the moment.

**Comment by simonw** [comment]
I'm going to ship what I've got as a new `datasette-app-support` release and close this issue.
